In [1]:
import numpy as np

In [7]:
###np.array(): Bir dizi oluşturur.
arr = np.array([1, 2, 3])
print(arr) 

[1 2 3]


In [9]:
###np.zeros(): Belirtilen şekilde sıfırlarla dolu bir dizi oluşturur.
 
zeros_arr = np.zeros((2, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
###np.ones(): Belirtilen şekilde birlerle dolu bir dizi oluşturur.
 
ones_arr = np.ones((2, 3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
##np.random.rand(): Belirtilen şekilde rastgele sayılar içeren bir dizi oluşturur (0 ile 1 arasında).
 
rand_arr = np.random.rand(3, 2)
print(rand_arr)

[[0.41272515 0.66267051]
 [0.67623337 0.4869906 ]
 [0.09801977 0.4608378 ]]


In [17]:
####np.reshape(): Bir dizinin şeklini değiştirir.
 
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [19]:
###np.dtype(): Bir dizinin veri tipini döndürür.
 
arr = np.array([1, 2, 3])
dtype = arr.dtype
print(dtype) 

int32


In [21]:
###np.sum(): Bir dizinin tüm elemanlarının toplamını döndürür.
 
arr = np.array([1, 2, 3])
sum_val = np.sum(arr)
print(sum_val)

6


In [23]:
###np.max(): Bir dizinin maksimum elemanını döndürür.
 
arr = np.array([1, 2, 3])
max_val = np.max(arr)
print(max_val)

3


In [25]:
###np.argmin(): Bir dizinin minimum elemanının indeksini döndürür.
 
arr = np.array([3, 1, 2])
argmin_val = np.argmin(arr)
print(argmin_val)

1


In [27]:
###np.concatenate(): İki veya daha fazla diziyi birleştirir.
 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

[1 2 3 4 5 6]
